services:
  ai-ranker-training:
    image: harbor.cloud.infn.it/datacloud-middleware/ai-ranker:devel-python3.11
    container_name: ai-ranker-training
    env_file:
      - .env
    volumes:
      - ./dataset:/dataset
    restart: unless-stopped
    command: bash -c "while true; do sleep 1; done"
    labels:
      ofelia.enabled: true
      ofelia.job-exec.feed.schedule: "@every 1m"
      ofelia.job-exec.feed.command: "python /app/src/main.py --training"
      ofelia.job-exec.feed.save-folder: /var/log
      ofelia.job-exec.feed.no-overlap: false

  ai-ranker-inference:
    image: harbor.cloud.infn.it/datacloud-middleware/ai-ranker:devel-python3.11
    container_name: ai-ranker-inference
    env_file:
      - .env
    volumes:
      - ./dataset:/dataset
    restart: unless-stopped
    command: python /app/src/main.py --inference

  ofelia:
    image: mcuadros/ofelia:0.3.13
    container_name: training-job-scheduler
    depends_on:
      - ai-ranker-training
    restart: unless-stopped
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - training-logs:/var/log

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.17.0
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
    command: mlflow server --host 0.0.0.0 --port 5000
    restart: unless-stopped

volumes:
  training-logs: